blank_issues_enabled: true
contact_links:
  - name: ðŸ’¬ Discussion / Questions
    url: https://github.com/Ponder001/SCKillFeed/discussions
    about: Ask questions or discuss ideas with the community

